# Path where simulation results will be saved
absolute_path: "/dtu-compute/msaca/simulated_data/diffraction"
session_name: "crystal_exp4"

# Mesh configuration
mesh_type: "cylinder"   # could be: cylinder, cube, custom
mesh_parameters:
  number_of_elements: 100  # alternative if mesh_density not given
  sample_height: 0.3   # cylinder height
  sample_radius: 3.0    # cylinder radius

# Materials (list of CIF files)
materials:
  parent_folder: "/dtu-compute/msaca/sliceA_diffraction/cif-files_and_theoretical_pd_spectra/cif"
  files:
    - 183960_FeCr2O4_chro.cif
    - 180326_Na(AlSi3O8)_alb.cif
    - 184824_Ca5(PO4)3Cl_chl.cif

# Probability (0–100) that an element is powder instead of a perfect crystal
powder_percentage: 50

# Experiment setup parameters
experiment:
  wavelength: 0.4        # Ångström
  pixel_size: 150.         # mm or your unit
  number_of_detector_pixels: 512     # number of pixels (square detector assumed)
  detector_distance: 150000  # distance in mm
  beam_width: 0.005         # mm
  number_of_angles: 181           # number of rotation angles
  number_of_translations: 192
  translation_distance: 0.0375
  polarization: false
  lorentz: false

crystal_quantile: 80





